# -*- coding: utf-8 -*-
"""AnalizadorLexico.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P34VzKrgSD9P89Ahur-nirYVAJcya4Y-
"""

# Detectando terminales y no terminales 
# A01209403 - Diana Estefania Ortiz Ledesma

# Variables globales
input = ''                               
dictionary = {}                           
flag = 0
line = 0

i = 0                                         
j = 0                                         

noT = {}                               
yesT = {} 

# Abrir y leer archivo de entrada                                                                        
file = open("input.txt", "r")              
while 1:
    line = line + 1
    # Leer por caracter                        
    caracter = file.read(1)                

    # Signos a identificar 
    symbols = { 1: "+", 2: "*", 3: "(", 4: ")" }    
    
    # Identificar si el caracter es un signo 
    # Si es un signo se guarda
    for i in symbols:                        
        if caracter == symbols[i]:           
            input += caracter            

    # Identificar si el caracter es un digito 
    if caracter.isdigit():                
        continue

    # Identificar si el caracter es alfabetico
    # Si es un caracter alfabetico se guarda 
    if caracter.isalpha():                  
        input += caracter                 

    # Identificar si el caracter es -
    # Si es - se guarda     
    if caracter == '-':                     
        input += caracter                

    # Identificar si el caracter es >
    # Si es > se guarda
    if caracter == '>':                   
        input += caracter                

    # Identificar si el caracter es espacio, tabulador o salto de linea
    # Si es cualquiera de los tres se guarda
    if caracter == '\n' or caracter == '\t' or caracter == ' ' :  
        dictionary [input] = line      

        # Identificar si es terminal o no terminal
        if input != "->":                
            if flag == 0:                 
                noT [input] = line
            if flag == 1:                  
                yesT [input] = line 

        if input == "->":
            flag = 1                       
        if caracter == '\n':
            flag = 0                         
        input = ''    

    # Finalizar si ya no hay caracteres                            
    if not caracter:                         
        break

# Cerrar archivo 
file.close()                                

# Copiar no terminales y terminales 
# Recuperar llaves
aux = noT.copy()                        
aux1 = yesT.copy()                          
aux3 = aux.keys()                            
aux4 = aux1.keys()                              

# Eliminar llaves de terminal 
# iguales a las de no terminal
for i in aux3:                              
    for j in aux4:                          
        if i == j:                       
            yesT.pop(i)        

terminal = []                                    
nonTerminal = []                                 

# Crear listas de terminales y no terminales
for i in noT:                           
    nonTerminal.append(i)                          

for j in yesT:
     terminal.append(j)                       

com = ', '.join(nonTerminal)               
comma = ', '.join(terminal)

# Escribir el resultado en un archivo de salida
output = open("output.txt", "w")    

output.write("Terminal: ") 
output.write(comma)
output.write("\n")

output.write("Non terminal: ")
output.write(com)
output.close()

# Imprimir en pantalla los resultados       
print("Terminal:", comma)
print("Non terminal:", com)